import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "abdus-next-app",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <a href=""></a>home
        </nav>
        {children}
        <footer>Footer</footer>
      </body>
    </html>
  );
};

export default RootLayout;
